in:
  type: file
  path_prefix: ./sample/sample
  parser:
    type: csv
    delimiter: ','
    charset: UTF-8
    header_line: true
    columns:
      - {name: id, type: long}
      - {name: username, type: string}
      - {name: email, type: string}
      - {name: country, type: string}
      - {name: balance, type: double}

exec:
  min_output_tasks: 1

out:
  type: file
  path_prefix: ./sample/encrypted_sample
  file_ext: ".csv.gpg"
  formatter:
    type: csv
    delimiter: "\t"
    newline: CRLF
    newline_in_field: LF
    charset: UTF-8
    quote_policy: MINIMAL
    quote: '"'
    escape: "\\"
    null_string: "\\N"
    default_timezone: 'UTC'
  encoders:
    - type: encryption
      public_key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        
        mDMEaOInhxYJKwYBBAHaRw8BAQdAr8cvn20amkJLM+14u8uofhao1430SMl1mDZw
        0A15owO0ImhpZXAudG8gPHRhbmhpZXAyMDEyMDAzQGdtYWlsLmNvbT6ImQQTFgoA
        QRYhBGVyXtKTbf1kevUiPIJclnCXaRLiBQJo4ieHAhsDBQkFo5qABQsJCAcCAiIC
        BhUKCQgLAgQWAgMBAh4HAheAAAoJEIJclnCXaRLixXkBAMFsaeb9Iy3b6Y654Og0
        8TEqcdbV4LcEg+B6tZ8XllsPAQClq9L7uKaQKc7JtUb7CIdIGzvQWCxiUpYMIpIb
        SLoBBrg4BGjiJ4cSCisGAQQBl1UBBQEBB0Cf7xc3yjS7173KqnVzZ96RPSrIno+l
        YjZs7KyndrdKcwMBCAeIfgQYFgoAJhYhBGVyXtKTbf1kevUiPIJclnCXaRLiBQJo
        4ieHAhsMBQkFo5qAAAoJEIJclnCXaRLiZ88A/i1yT3aMY1rhoOS0q/EPNMvW87EL
        6rtI9dn1yzSpTPM1AQCaK9CzSK6to4i+xkZmDQaeouAlS/YpvU16hhCwxnhJCQ==
        =a/vy
        -----END PGP PUBLIC KEY BLOCK-----
      ascii_armor: true
      with_compression: true
      compression_type: BZIP2
